;; Packages and themes
(package! nerd-icons)
(package! cyberpunk-theme)
(package! zoom)
(package! undo-tree)
(package! multiple-cursors)
(package! evil-matchit)
(package! key-chord)
(package! all-the-icons-completion)
(package! gcmh)
(package! ace-window)
(package! sweet-theme)
