;; Packages and themes
(package! nerd-icons)
(package! doom-themes)
(package! spacemacs-theme)
(package! cyberpunk-theme)
(package! zoom)
(package! undo-tree)
(package! atom-one-dark-theme)
(package! multiple-cursors)
(package! sweet-theme)
(package! evil-matchit)
(package! key-chord)
(package! all-the-icons-completion)
(package! kaolin-themes)
(package! gcmh)
